name: organization-labels
description: Label management across organization repositories

branding:
  icon: zap
  color: gray-dark

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/src/mirror-labels "$GITHUB_WORKSPACE/organization-labels.json"
      shell: bash
    - run: bash -c "env | sort"
      shell: bash
    - run: cat $GITHUB_EVENT_PATH
      shell: bash
